export const SEND_FACE_GET_IMAGES = "SEND_FACE_GET_IMAGES";
export const FACEDETECTING_LOADING = "FACEDETECTING_LOADING";

export const GET_EVENTDETAIL = "GET_EVENTDETAIL";
export const EVENTDETAIL_LOADING = "EVENTDETAIL_LOADING";