export const SEND_FACE_GET_IMAGES = "SEND_FACE_GET_IMAGES";
export const FACEDETECTING_LOADING = "FACEDETECTING_LOADING";

export const GET_EVENTDETAIL = "GET_EVENTDETAIL";
export const EVENTDETAIL_LOADING = "EVENTDETAIL_LOADING";

export const SELECTALL_IMAGES = "SELECTALL_IMAGES";
export const DESELECTALL_IMAGES = "DESELECTALL_IMAGES"
export const SELECT_IMAGE = "SELECT_IMAGE";
export const SELECT_IMAGE_DECK = "SELECT_IMAGE_DECK";
export const DESELECT_IMAGE = "DESELECT_IMAGE";
export const DESELECT_IMAGE_DECK = "DESELECT_IMAGE_DECK";